version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: navanin-zoraxy_zoraxy_1
      APP_PORT: 8005
      PROXY_AUTH_ADD: "false"
  zoraxy:
    image: zoraxydocker/zoraxy:3.1.0
    hostname: zoraxy
    ports:
      - 443:443
    volumes:
      - ${APP_DATA_DIR}/data:/opt/zoraxy/config/
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime
    environment:
      PORT: "8005"
      FASTGEOIP: "true"
