version: "3.7"

services:
  portainer:
    privileged: true
    network_mode: host
    image: portainer/portainer-ce:2.19.5
    container_name: portainer
    environment:
      - TZ=Asia/Tomsk
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${APP_DATA_DIR}/data/portainer:/data
      - ${APP_DATA_DIR}/default-password:/default-password
    ports:
      - "9000:9000"
    restart: always